### ISSUE TITLE
`keras.utils.audio_dataset_from_directory` breaks when `sampling_rate` is specified

### ISSUE THREAD

**Issue by abheesht17** [keras-team/tf-keras#100]
Reproduced the bug here: https://colab.research.google.com/drive/194dwSqmwgdCnO_-HWT56h-R8RrQ9v8fH?usp=sharing

**Comment by sonali-kumari1** [comment]
Hi @abheesht17,

Thanks for reporting the issue. I reproduced the code shared by you and it doesn't seem to generate any error. 

Attaching [gist](https://colab.sandbox.google.com/gist/sonali-kumari1/4332854b58147cd8de211b8769d4fb56/-keras-utils-audio_dataset_from_directory-not-working-with-sampling_rate.ipynb) for your reference. 

Please try running your code in the latest version of keras and tensorflow.
