### ISSUE TITLE
Calling a model and using model.predict yields different results for the same input

### ISSUE THREAD

**Issue by tobiasarndt** [keras-team/tf-keras#135]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes, see in standalone code to reproduce behaviour
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey 12.4
- TensorFlow installed from (source or binary): installed using `pip install tensorflow-macos`and `pip install tensorflow-metal`
- TensorFlow version (use command below): v2.13.0-rc2-7-g1cb1a030a62 2.13.0
- Python version: 3.10.9
- Bazel version (if compiling from source):
- GPU model and memory: Apple M1, 16 GB LPDDR4
- Exact command to reproduce: see in standalone code to reproduce behaviour

**Describe the problem**.

When I call model(data) and model.predict(data) i get different outputs. 
I provided a minimal working example below.

**Describe the current behavior**.

When I call model(data) and model.predict(data) i get different outputs. 

**Describe the expected behavior**.

Calling model(data) and model.predict(data) should give the same output

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**.

```python3
from tensorflow import keras
import numpy as np

nn = keras.Sequential([
  keras.layers.Input((1)),
  keras.layers.Dense(2,activation = 'relu'),
  keras.layers.Dense(1,activation='linear')
])

nn.compile()

data = np.ones((1))

print(nn(data, training=False))
print(nn.predict(data))
```

**Comment by tGrothmannFluffy** [comment]
Reopening this because there is no solution yet.

I'm having a similar issue with [a yolo network](https://keras.io/examples/vision/yolov8/). I'm getting totally different values and differently formatted output for calling the model and .predict.
