### ISSUE TITLE
tf.keras.layers.Normalization(invert=True) does not restore from save

### ISSUE THREAD

**Issue by mzakharo** [keras-team/tf-keras#264]
**System information**.
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04
- TensorFlow installed from (source or binary):  tf-nightly from pip
- TensorFlow version (use command below): 2.13.0-dev20230212
- Python version:  3.10.6
- Bazel version (if compiling from source):
- GPU model and memory:  CPU/N/A
- Exact command to reproduce: run the code below:

**Describe the problem**.

`keras.models.load_model()` does not load `tf.keras.layers.Normalization` layer with `invert=True`.

**Describe the current behavior**.

It seems to omit `invert=True` flag when loading (or saving) the model.

**Describe the expected behavior**.

original trained and saved/loaded model output the same when using `Normalization` with `invert=True`.

**Standalone code to reproduce the issue**.

```python
import numpy as np
import pandas as pd
import sys
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
print(tf.__version__)

dataset = pd.read_csv('https://raw.githubusercontent.com/mzakharo/micropython/tubby/ports/esp32/orp2.csv')
train_dataset = dataset.sample(frac=0.9, random_state=0)
train_features = train_dataset.copy()
train_labels = train_features.pop('orp')

inorm = tf.keras.layers.Normalization(axis=-1, input_shape=[2, ])
inorm.adapt(np.array(train_features))
onorm = tf.keras.layers.Normalization(axis=-1, invert=True)
onorm.adapt(train_labels)

def build_and_compile_model(inorm, onorm):
  model = keras.Sequential([
      inorm,
      layers.Dense(10, activation='relu'),
      layers.Dense(1), 
     onorm,
  ])
  model.compile(loss='mean_squared_error', optimizer='adam')
  return model
model = build_and_compile_model(inorm, onorm)
history = model.fit(
    train_features,
    train_labels,
    validation_split=0.1,
    verbose=0, epochs=10)
fname = 'model.h5'
model.save(fname)

p0 = 7.6 
p1 = 0.85
v = model.predict([(p0, p1)], verbose=0)[0]
print('original output: ', v)
lmodel = keras.models.load_model(fname)
v = lmodel.predict([(p0, p1)], verbose=0)[0]
print('restored output: ', v)


```

**logs**.
```
original output:  [667.36383]
restored output:  [-8.889455]
```

**Comment by dr-spa** [comment]
The [code](https://colab.research.google.com/gist/Frightera/0323a8686352fa949a77fb21d2f6f125/17556-repro.ipynb) works well in TF v2.15, but in v2.16.1 it throws an exception:
->Colab output:
2.16.1
/usr/local/lib/python3.10/dist-packages/keras/src/layers/preprocessing/normalization.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-1-be402e2aabb4>](https://localhost:8080/#) in <cell line: 17>()
     15 inorm.adapt(np.array(train_features))
     16 onorm = tf.keras.layers.Normalization(axis=-1, invert=True)
---> 17 onorm.adapt(train_labels)
     18 
     19 def build_and_compile_model(inorm, onorm):

[/usr/local/lib/python3.10/dist-packages/keras/src/layers/preprocessing/normalization.py](https://localhost:8080/#) in adapt(self, data)
    226 
    227         if not self.built:
--> 228             self.build(input_shape)
    229         else:
    230             for d in self._keep_axis:

UnboundLocalError: local variable 'input_shape' referenced before assignment.
->End

->Reproduction:
!pip install tensorflow==2.16.2

import numpy as np
import pandas as pd
import sys
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
print(tf.__version__)
dataset = pd.read_csv('https://raw.githubusercontent.com/mzakharo/micropython/tubby/ports/esp32/orp2.csv')
train_dataset = dataset.sample(frac=0.9, random_state=0)
train_features = train_dataset.copy()
train_labels = train_features.pop('orp')
inorm = tf.keras.layers.Normalization(axis=-1, input_shape=[2, ])
inorm.adapt(np.array(train_features))
onorm = tf.keras.layers.Normalization(axis=-1, invert=True)
onorm.adapt(train_labels)
def build_and_compile_model(inorm, onorm):
  model = keras.Sequential([
      inorm,
      layers.Dense(10, activation='relu'),
      layers.Dense(1), 
      onorm,
  ])
  model.compile(loss='mean_squared_error', optimizer='adam')
  return model
model = build_and_compile_model(inorm, onorm)
history = model.fit(
    train_features,
    train_labels,
    validation_split=0.1,
    verbose=1, epochs=10)
fname = 'model.h5'
model.save(fname)
p0 = 7.6 
p1 = 0.85
v = model.predict([(p0, p1)], verbose=0)[0]
print('original output: ', v)
lmodel = keras.models.load_model(fname)
v = lmodel.predict([(p0, p1)], verbose=0)[0]
print('restored output: ', v)

->End

Adding the tf.keras.layers.Input layer with the shape removes the "/usr/local/lib/python3.10/dist-packages/keras/src/layers/preprocessing/normalization.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead." part of the error, but the "UnboundLocalError: local variable 'input_shape' referenced before assignment." remains.

**Comment by dr-spa** [comment]
> The [code](https://colab.research.google.com/gist/Frightera/0323a8686352fa949a77fb21d2f6f125/17556-repro.ipynb) works well in TF v2.15, but in v2.16.1 it throws an exception: ->Colab output: 2.16.1 /usr/local/lib/python3.10/dist-packages/keras/src/layers/preprocessing/normalization.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead. super().**init**(**kwargs)
> 
> UnboundLocalError Traceback (most recent call last) in <cell line: 17>() 15 inorm.adapt(np.array(train_features)) 16 onorm = tf.keras.layers.Normalization(axis=-1, invert=True) ---> 17 onorm.adapt(train_labels) 18 19 def build_and_compile_model(inorm, onorm):
> 
> [/usr/local/lib/python3.10/dist-packages/keras/src/layers/preprocessing/normalization.py](https://localhost:8080/#) in adapt(self, data) 226 227 if not self.built: --> 228 self.build(input_shape) 229 else: 230 for d in self._keep_axis:
> 
> UnboundLocalError: local variable 'input_shape' referenced before assignment. ->End
> 
> ->Reproduction: !pip install tensorflow==2.16.1
> 
> import numpy as np import pandas as pd import sys import tensorflow as tf from tensorflow import keras from tensorflow.keras import layers print(tf.**version**) dataset = pd.read_csv('https://raw.githubusercontent.com/mzakharo/micropython/tubby/ports/esp32/orp2.csv') train_dataset = dataset.sample(frac=0.9, random_state=0) train_features = train_dataset.copy() train_labels = train_features.pop('orp') inorm = tf.keras.layers.Normalization(axis=-1, input_shape=[2, ]) inorm.adapt(np.array(train_features)) onorm = tf.keras.layers.Normalization(axis=-1, invert=True) onorm.adapt(train_labels) def build_and_compile_model(inorm, onorm): model = keras.Sequential([ inorm, layers.Dense(10, activation='relu'), layers.Dense(1), onorm, ]) model.compile(loss='mean_squared_error', optimizer='adam') return model model = build_and_compile_model(inorm, onorm) history = model.fit( train_features, train_labels, validation_split=0.1, verbose=1, epochs=10) fname = 'model.h5' model.save(fname) p0 = 7.6 p1 = 0.85 v = model.predict([(p0, p1)], verbose=0)[0] print('original output: ', v) lmodel = keras.models.load_model(fname) v = lmodel.predict([(p0, p1)], verbose=0)[0] print('restored output: ', v)
> 
> ->End
> 
> Adding the tf.keras.layers.Input layer with the shape removes the "/usr/local/lib/python3.10/dist-packages/keras/src/layers/preprocessing/normalization.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead." part of the error, but the "UnboundLocalError: local variable 'input_shape' referenced before assignment." remains.

In the tf_nightly version (2.17.0) the issue also persists.
