### ISSUE TITLE
cannot find reference 'keras in __init__ py __init__ py

### ISSUE THREAD

**Issue by raul-parada** [keras-team/tf-keras#295]
I have a code for LSTM including transformers.

The error is the following: 
```
Traceback (most recent call last):
  File "C:\UsersLSTM_TL.py", line 12, in <module>
    from tensorflow.keras.layers import Input, Transformer
ImportError: cannot import name 'Transformer' from 'tensorflow.keras.layers' (C:\Users\cttc\anaconda3\envs\testenv\lib\site-packages\keras\api\_v2\keras\layers\__init__.py)
```

The line is:
... 
`model.add(Transformer(num_layers=6, d_model=64, num_heads=8, dff=256, dropout=0.2)) 
`...

In the imports I do have:
```
from tensorflow.keras.layers import Input, Transformer
from tensorflow.keras.models import Model
from tensorflow.keras import optimizers
```

In which the keras part appears with a red underline with the following error: "`cannot find reference 'keras in __init__ py __init__ py`".

I'm running this on:
- Windows 10 64bits
- Anaconda3 2022.10 (Python 3.9.13 64-bit)
- PyCharm 2022.3.1
- Inside Conda Env setup as Python 3.10.4 (previously installed). 
I've installed tensorflow on Administrator Anaconda Prompt with conda install tensorflow (it was successful)

**Comment by CMMuhammadTech** [comment]
i ran into the same issue, i suggest you install the package alone, make sure to install the same version as your tensorflow package. FInd the package in the in your site-packages, copy and paste files into your tensorflow package that is located in site-packages as well.
