### ISSUE TITLE
Model subclass with functional instances can cause weird side effects

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/tf-keras#351]
**Describe the problem**.
Let's say you are working on a model base class that derives from `keras.Model` and provides some additional functionality. It is intended to be used with both functional and subclass patterns, similar to `keras.Model`.

In this case you can run into a weird issue, where any code making a functional instantiation of your subclass class will permanently rewrite the inheritance tree of your subclass class so all future instantiation must also be functional due to [this line](https://github.com/keras-team/keras/blob/069b8d3bc15dbb13b6311fee52c91d6a78985bfb/keras/engine/training.py#L4047).

**Describe the current behavior**.
The colab below is probably most useful to understand the issue. Given an object hierarchy that looks like:
```
keras.Model
|
ModelSubclass (either functional or not)
|
ModelSubclassSubclass (not functional)
```
You can go from being able to create `ModelSubclassSubclass` without issue, and then only by making a functional instance of `ModelSubclass`, break all future `ModelSubclassSubclass` invocations.

This is a quite unexpected side effect, and make it difficult to provide a generic subclass of `keras.Model` with extra functionality.

**Describe the expected behavior**.
I would not expect making a functional instantiation of `ModelSubclass` to have any side effects on the class hierarchy itself.

**Standalone code to reproduce the issue**.

https://colab.sandbox.google.com/gist/mattdangerw/2249925130289beb8c10361c7d6fccdd/inheritance-bug.ipynb

**Comment by tilakrayal** [comment]
@mattdangerw,
I tried to execute the mentioned code on tf-nightly with the keras3.0 version and it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/21c03548b0ad4dca78899915fd207a54/untitled.ipynb). Thank you!
