### ISSUE TITLE
tf.keras.models.model_from_json() missing a safe_mode parameter

### ISSUE THREAD

**Issue by epetrovski** [keras-team/tf-keras#44]
When loading a model with a lambda layer from a json model config, TensorFlow/Keras 2.13 provides the following error:

`
ValueError: Requested the deserialization of a Lambda layer with a Python 'lambda' inside it. This carries a potential risk of arbitrary code execution and thus it is disallowed by default. If you trust the source of the saved model, you can pass 
'safe_mode=False' to the loading function in order to allow Lambda layer loading.
`

However `tf.keras.models.model_from_json()` does not have a `safe_mode` parameter. So there does not seem to be a way to load models with lamda layers using a json config. This issue does not appear in TensorFlow/Keras 2.12

### Standalone code to reproduce the issue

```shell
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Input, Lambda

inputs = Input(shape=(1,))
x = Lambda(lambda x: x*2)(inputs)
out = Dense(1)(x)
model = Model(inputs=inputs,outputs=out)

model_config = model.to_json()
tf.keras.models.model_from_json(model_config)
```

**Comment by kaushal20383** [comment]
problem still exist on 2.14.

**Comment by woozway** [comment]
Same issue here.  Any news?  Thanks a lot.

**Comment by zehao-intel** [comment]
Hi,
May I know if there is any plan of fixing this issue?
Thanks~

**Comment by SteveWang1992** [comment]
Same issue happened to me. Using TensorFlow 2.14.0.

**Comment by djpetti** [comment]
Here is a possible workaround:

```python
from keras.src.saving import serialization_lib
serialization_lib.enable_unsafe_deserialization()
```

After running this, you should be able to deserialize `lambda` layers.

**Comment by epetrovski** [comment]
> Here is a possible workaround:
> 
> ```python
> from keras.src.saving import serialization_lib
> serialization_lib.enable_unsafe_deserialization()
> ```
> 
> After running this, you should be able to deserialize `lambda` layers.

I can confirm that this works. Thanks!

**Comment by sachinprasadhs** [comment]
Thanks for confirming, could you please close the issue as well

**Comment by epetrovski** [comment]
As of 2.14, the issue seems to be gone even when not running `serialization_lib.enable_unsafe_deserialization()`

**Comment by fashni** [comment]
> As of 2.14, the issue seems to be resolved even without calling `serialization_lib.enable_unsafe_deserialization()`

The issue still persists in 2.16.1

```
ValueError: The `{arg_name}` of this `Lambda` layer is a Python lambda. Deserializing it is unsafe. If you trust the source of the config artifact, you can override this error by passing `safe_mode=False` to `from_config()`, or calling `keras.config.enable_unsafe_deserialization().
>>>
>>> tf.__version__
'2.16.1'
>>> tf.keras.__version__
'3.3.3'
```

**Comment by fashni** [comment]
> As of 2.14, the issue seems to be resolved even without calling `serialization_lib.enable_unsafe_deserialization()`

The issue is still there in 2.16.1

```
ValueError: The `{arg_name}` of this `Lambda` layer is a Python lambda. Deserializing it is unsafe. If you trust the source of the config artifact, you can override this error by passing `safe_mode=False` to `from_config()`, or calling `keras.config.enable_unsafe_deserialization().
>>> tf.keras.models.model_from_json(model_config, safe_mode=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: model_from_json() got an unexpected keyword argument 'safe_mode'
>>> tf.__version__
'2.16.1'
>>> tf.keras.__version__
'3.3.3'
>>>
```

**Comment by SedCore** [comment]
I solved the issue using the following:
`import tensorflow.keras.config as tfconfig`
`tfconfig.enable_unsafe_deserialization()`
Hope it helps.

**Comment by giorgio-denunzio** [comment]
> I solved the issue using the following: `import tensorflow.keras.config as tfconfig` `tfconfig.enable_unsafe_deserialization()` Hope it helps.

Thank you very much. I will try.
