### ISSUE TITLE
keras create/load model fails on Apple M2 cpu.  Same code works on Ryzen

### ISSUE THREAD

**Issue by drmatthewclark** [keras-team/tf-keras#46]
[tf_env.txt](https://github.com/keras-team/keras/files/11970574/tf_env.txt)

You can obtain the TensorFlow version with:
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
result:
v2.13.0-rc2-7-g1cb1a030a62 2.13.0

Can't load a keras model that I just created.  The issue is not specific to Adam; all of the optimizers have the same issue.

**Describe the problem**.

code:

      from tensorflow import keras
      
      
      optimizer = keras.optimizers.Adam()
      
      vh  = keras.Input(shape=(2,3), name = 'vh')
      v1  = keras.layers.Dense(512)(vh)
      
      output  = keras.layers.Dense(1, activation='softmax', name='prediction')(v1)
      
      model = keras.Model(inputs=vh, outputs=[output], name="antibody_model")
      
      model.compile(optimizer=optimizer )
      
      model.save('nn_model.keras')
      test = keras.models.load_model('nn_model.keras')

output:

the legacy Adam is missing the method  "build".  This same code works on non-mac platforms.

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.
Traceback (most recent call last):
  File "/Users/matthewclark/eclipse-workspace/antibody_classification/test/test.py", line 17, in <module>
    test = keras.models.load_model('nn_model.keras')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 230, in load_model
    return saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 275, in load_model
    raise e
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 240, in load_model
    model = deserialize_keras_object(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/saving/serialization_lib.py", line 710, in deserialize_keras_object
    instance.compile_from_config(compile_config)
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/engine/training.py", line 3582, in compile_from_config
    self.optimizer.build(self.trainable_variables)
    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/optimizers/legacy/optimizer_v2.py", line 997, in __getattribute__
    raise e
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/optimizers/legacy/optimizer_v2.py", line 987, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Adam' object has no attribute 'build'

**Comment by tilakrayal** [comment]
@drmatthewclark,
I tried to execute the mentioned code on Apple M1 with the tf-nightly(2.15.0-dev20230927) and it was executed without any fail or error. Kindly find the screenshot below for the reference.
<img width="567" alt="image (20)" src="https://github.com/keras-team/tf-keras/assets/81610181/f24b9b0d-2e99-4d63-bbb8-b1c6f9288fca">

Thank you!

**Comment by palminha** [comment]
@tilakrayal i confirm that with tf-nightly the error it seems to be fixed
```
% pipenv graph
...
tf-nightly==2.15.0.dev20230928
└── tf-nightly-macos [required: ==2.15.0-dev20230928, installed: 2.15.0.dev20230928]
```


it seems it solves the error
```
% pipenv run adam
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:Skipping variable loading for optimizer 'Adam', because it has 9 variables whereas the saved optimizer has 1 variables. 
```

I also reported the same finding here: https://github.com/tensorflow/tensorflow/issues/61915#issuecomment-1738816019

**Comment by EswarJanjanam** [comment]
I'm using mac m1 pro and tensorflow version is 2.14.0. I was facing the same error "AttributeError: 'Adam' object has no attribute 'build'" while loading the saved model, if I save the model as below
`model = Sequential()
model.add(Embedding(MAX_FEATURES+1, 32))
model.add(Bidirectional(LSTM(32, activation='tanh')))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='BinaryCrossentropy', optimizer='Adam')
model.fit(train, epochs=1, validation_data=val)
model.save('data/model_data.keras')`

I updated the optimizer and it is working fine now
import tensorflow as tf
`model.compile(loss='BinaryCrossentropy', optimizer=tf.keras.optimizers.Adam())`

**Comment by nkovela1** [comment]
@EswarJanjanam The fix is on tf-nightly. Please do `pip install tf-nightly` and see if your code works, thanks!

**Comment by phpmac** [comment]
```
$pip install tf-nightly
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly
```

**Comment by phpmac** [comment]
> ```
> $pip install tf-nightly
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
> ERROR: No matching distribution found for tf-nightly
> ```

Crap, it's my mirroring problem, sorry!

But it didn't solve the problem.


```

AttributeError: 'Adam' object has no attribute 'build'


```

**Comment by hanamurayuki** [comment]
> $pip install tf-nightly
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
> ERROR: No matching distribution found for tf-nightly

Same error exists on M2 mac.

```
AttributeError: 'Adam' object has no attribute 'build'
```


.h5 format is one of solution instead of .keras format for now.
I hope I can save model as .keras format.

**Comment by phpmac** [comment]
> > $pip install tf-nightly
> > Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> > ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
> > ERROR: No matching distribution found for tf-nightly
> 
> Same error exists on M2 mac.
> 
> ```
> AttributeError: 'Adam' object has no attribute 'build'
> ```
> 
> .h5 format is one of solution instead of .keras format for now. I hope I can save model as .keras format.

Yeah, I mean can't he just automatically adapt to the solution?

**Comment by MurtadhaInit** [comment]
Having the exact same issue, and can confirm that `tf-nightly` is NOT working for me.

**Comment by richardokonicha** [comment]
same issue

**Comment by saarangbond** [comment]
Having the same issue as well on Mac M1. The same code works on cloud workstation on linux.

**Comment by eyash24** [comment]
After much trial and error, installing keras-nightly solved the issue and my model started working.
