### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by iamrajee** [keras-team/tf-keras#470]
Facing Below Error
```
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-37-96313394c236>](https://localhost:8080/#) in <module>      1 H = model.fit(trainX, 
      2               trainY,----> 3               validation_data=(testX, testY))


1 frames



[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)     65     except Exception as e:  # pylint: disable=broad-except     66       filtered_tb = _process_traceback_frames(e.__traceback__)---> 67       raise e.with_traceback(filtered_tb) from None     68     finally:     69       del filtered_tb
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)     53     ctx.ensure_initialized()     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:     57     if name is not None:
```

**Comment by adeniran-segun23** [comment]
import keras
from keras.src.applications import VGG16
from keras.src.preprocessing.image import ImageDataGenerator
from tensorflow import float32

# DATA AUGMENTATION

train_examples = 825
test_examples = 104
validation_examples = 119
batch_size = 20
Img_height = Img_width = 224

train_datagen = ImageDataGenerator(
    rescale=1.0 / 255, rotation_range=15,
    zoom_range=(0.95, 0.95),
    horizontal_flip=True, vertical_flip=True,
    data_format="channels_last", width_shift_range=0.2,
    height_shift_range=0.2,
    dtype=float32

)

test_datagen = ImageDataGenerator(
    rescale=1.0 / 255, width_shift_range=0.2,
    height_shift_range=0.2,
    dtype=float32
)

validation_datagen = ImageDataGenerator(
    rescale=1.0 / 255, width_shift_range=0.2,
    height_shift_range=0.2,
    dtype=float32
)

train_set = train_datagen.flow_from_directory(
    "data/train",
    target_size=(224, 224),
    batch_size=20,
    color_mode="rgb", class_mode="binary",
    shuffle=True,
    seed=123
)
validation_set = validation_datagen.flow_from_directory(
    "data/validation", target_size=(224, 224),
    batch_size=batch_size,
    color_mode="rgb", class_mode="binary",
    shuffle=True,
    seed=123
)

test_set = test_datagen.flow_from_directory(
    "data/test", target_size=(224, 224),
    batch_size=batch_size, color_mode="rgb",
    class_mode="binary", shuffle=True,
    seed=123
)

model = VGG16(input_shape=(224, 224, 3), weights="imagenet")

METRICS = [
    keras.metrics.BinaryAccuracy(name="accuracy"),
    keras.metrics.Precision(name="precision"),
    keras.metrics.Recall(name="recall"),
    keras.metrics.AUC(name="auc")
]
model.compile(
    optimizer=keras.optimizers.legacy.Adam(learning_rate=3e-4),
    loss=[keras.losses.binary_crossentropy(from_logits=False)],
    metrics=METRICS,
)

model.fit(
    train_set,
    epochs=5,
    verbose=2,
    steps_per_epoch=train_examples//batch_size,
    validation_data=validation_set,
    validation_steps=validation_examples//batch_size,
    callbacks=[keras.callbacks.ModelCheckpoint("SHOULDER_IMG/images/")]
)

model.evaluate(validation_set, verbose=2)
model.evaluate(test_set, verbose=2)
![ERROR WARNING](https://github.com/keras-team/tf-keras/assets/150259705/865ef8c3-5805-4b62-9e1d-680463bdd8ae)
Traceback (most recent call last):
  File "C:\Users\INCHBAY SERVICES LTD\PycharmProjects\MY_PROJECT\VGG-16.py", line 69, in <module>
    loss=[keras.losses.binary_crossentropy(from_logits=False)],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\INCHBAY SERVICES LTD\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\INCHBAY SERVICES LTD\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\util\dispatch.py", line 1254, in op_dispatch_handler
    result = api_dispatcher.Dispatch(args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Missing required positional argument

Process finished with exit code 1

**Comment by adeniran-segun23** [comment]
> import keras from keras.src.applications import VGG16 from keras.src.preprocessing.image import ImageDataGenerator from tensorflow import float32
> 
> # DATA AUGMENTATION
> train_examples = 825 test_examples = 104 validation_examples = 119 batch_size = 20 Img_height = Img_width = 224
> 
> train_datagen = ImageDataGenerator( rescale=1.0 / 255, rotation_range=15, zoom_range=(0.95, 0.95), horizontal_flip=True, vertical_flip=True, data_format="channels_last", width_shift_range=0.2, height_shift_range=0.2, dtype=float32
> 
> )
> 
> test_datagen = ImageDataGenerator( rescale=1.0 / 255, width_shift_range=0.2, height_shift_range=0.2, dtype=float32 )
> 
> validation_datagen = ImageDataGenerator( rescale=1.0 / 255, width_shift_range=0.2, height_shift_range=0.2, dtype=float32 )
> 
> train_set = train_datagen.flow_from_directory( "data/train", target_size=(224, 224), batch_size=20, color_mode="rgb", class_mode="binary", shuffle=True, seed=123 ) validation_set = validation_datagen.flow_from_directory( "data/validation", target_size=(224, 224), batch_size=batch_size, color_mode="rgb", class_mode="binary", shuffle=True, seed=123 )
> 
> test_set = test_datagen.flow_from_directory( "data/test", target_size=(224, 224), batch_size=batch_size, color_mode="rgb", class_mode="binary", shuffle=True, seed=123 )
> 
> model = VGG16(input_shape=(224, 224, 3), weights="imagenet")
> 
> METRICS = [ keras.metrics.BinaryAccuracy(name="accuracy"), keras.metrics.Precision(name="precision"), keras.metrics.Recall(name="recall"), keras.metrics.AUC(name="auc") ] model.compile( optimizer=keras.optimizers.legacy.Adam(learning_rate=3e-4), loss=[keras.losses.binary_crossentropy(from_logits=False)], metrics=METRICS, )
> 
> model.fit( train_set, epochs=5, verbose=2, steps_per_epoch=train_examples//batch_size, validation_data=validation_set, validation_steps=validation_examples//batch_size, callbacks=[keras.callbacks.ModelCheckpoint("SHOULDER_IMG/images/")] )
> 
> model.evaluate(validation_set, verbose=2) model.evaluate(test_set, verbose=2) ![ERROR WARNING](https://user-images.githubusercontent.com/150259705/281425548-865ef8c3-5805-4b62-9e1d-680463bdd8ae.png) Traceback (most recent call last): File "C:\Users\INCHBAY SERVICES LTD\PycharmProjects\MY_PROJECT\VGG-16.py", line 69, in loss=[keras.losses.binary_crossentropy(from_logits=False)], ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\INCHBAY SERVICES LTD\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler raise e.with_traceback(filtered_tb) from None File "C:\Users\INCHBAY SERVICES LTD\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\util\dispatch.py", line 1254, in op_dispatch_handler result = api_dispatcher.Dispatch(args, kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: Missing required positional argument
> 
> Process finished with exit code 1

I NEED HELP WITH CODE ERROR

**Comment by ushasrivanama** [comment]
-> 123     raise e.with_traceback(filtered_tb) from None
    124 finally:
    125     del filtered_tb

File ~\anaconda3\lib\site-packages\keras\src\trainers\trainer.py:854, in Trainer._pythonify_logs(self, logs)
    852 def _pythonify_logs(self, logs):
    853     result = {}
--> 854     for key, value in sorted(logs.items()):
    855         if isinstance(value, dict):
    856             result.update(self._pythonify_logs(value))

AttributeError: 'NoneType' object has no attribute 'items
