### ISSUE TITLE
TimeDistributed model compatibility

### ISSUE THREAD

**Issue by andreped** [keras-team/tf-keras#575]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 and Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.10.0a20220604 (nightly)
- Python version: 3.8.10

**Describe the problem**.

Just came across something rather strange. Seems like some architectures in keras.applications does not work directly with TimeDistributed.

For an example, you have the three architectures MobileNetV2, *V3, and a ConvNeXt-S architecture. If you use MobileNetV2 it works, but for the two others it does not.

AFAIK, eager mode is enabled by default, so I don't see why this fails here? I also have not compiled the model yet or run it, where I would then do `run_eagerly=True`, if necessary.

**Describe the current behavior**.

Fails for some models. MobileNetV3 also fails in TF 2.8.0, so it has apparently been an issue a while.

**Describe the expected behavior**.

Should expect the same behaviour for all model applications in this scenario.

**Potential solution**.

I think this has to do with how the `output_shape` is dynamically fetched, which may not work as intended for some layers? Perhaps layers like TFOpLambda and LayerScale require that the `compute_output_shape` methods are implemented to work as expected?

**Standalone code to reproduce the issue**.

Works for MobileNetV2 and not for the two other.
```
import keras
from keras.applications import MobileNetV2, MobileNetV3Small, ConvNeXtSmall

input_ = keras.layers.Input(shape=(8, 224, 224, 3))

# base_model  = MobileNetV2(include_top=True, input_shape=(224, 224, 3))
base_model = MobileNetV3Small(include_top=True, input_shape=(224, 224, 3))
# base_model = ConvNeXtSmall(include_top=True, input_shape=(224, 224, 3))

output = keras.layers.TimeDistributed(base_model)(input_)
model = keras.Model(inputs=input_, outputs=output)
```

**Source code / logs**.

Error prompt for MobileNetV3:

```
Traceback (most recent call last):
File “.\test_timedistributed.py”, line 12, in
output = keras.layers.TimeDistributed(base_model)(input_)
File “C:\Users\47955\workspace\sandbox\venv\lib\site-packages\keras\utils\traceback_utils.py”, line 70, in error_handler
raise e.with_traceback(filtered_tb) from None
File “C:\Users\47955\workspace\sandbox\venv\lib\site-packages\keras\engine\base_layer.py”, line 879, in compute_output_shape
raise NotImplementedError(
NotImplementedError: Exception encountered when calling layer “time_distributed” (type TimeDistributed).

Please run in eager mode or implement the compute_output_shape method on your layer (TFOpLambda).

Call arguments received by layer “time_distributed” (type TimeDistributed):
• inputs=tf.Tensor(shape=(None, 8, 224, 224, 3), dtype=float32)
• training=False
• mask=None
```

and for ConvNeXtSmall:

```
Traceback (most recent call last):
File “.\test_timedistributed.py”, line 10, in
output = keras.layers.TimeDistributed(base_model)(input_)
File “C:\Users\47955\workspace\sandbox\venv\lib\site-packages\keras\utils\traceback_utils.py”, line 70, in error_handler
raise e.with_traceback(filtered_tb) from None
File “C:\Users\47955\workspace\sandbox\venv\lib\site-packages\keras\engine\base_layer.py”, line 879, in compute_output_shape
raise NotImplementedError(
NotImplementedError: Exception encountered when calling layer “time_distributed” (type TimeDistributed).

Please run in eager mode or implement the compute_output_shape method on your layer (LayerScale).

Call arguments received by layer “time_distributed” (type TimeDistributed):
• inputs=tf.Tensor(shape=(None, 8, 224, 224, 3), dtype=float32)
• training=None
• mask=None`
```

**Comment by amadou1998** [comment]
I m currently seeing this error again in 2.16.1

**Comment by hertschuh** [comment]
Hi @amadou1998 , I ran the code from the initial issue report with 2.16.1 with both Keras 3 and tf-keras (Keras 2) and I did not get any error message. Can you provide specific repro steps?

**Comment by vikkubaligas** [comment]
`import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, LSTM, Concatenate, Dense, TimeDistributed
from tensorflow.keras.models import Model

tf.__version__, tf.keras.__version__
## ('2.16.1', '3.3.3')


input_icd = Input(shape=(10,))
embedding_icd = Embedding(input_dim = 100+1, output_dim = 16, mask_zero=False)(input_icd)
lstm_icd1 = LSTM(units=32, return_sequences=True)(embedding_icd) 
lstm_icd2 = LSTM(units=32, return_sequences=False)(lstm_icd1) 
model = Model(inputs=input_icd, outputs=lstm_icd2)

input_full = Input(shape=(10,10))
td = TimeDistributed(model)(input_full)
model2 = Model(inputs=input_full,outputs=td)`

You do this, to get the error. 

In my case, tf = 2.16.1 and tf.keras = 3.3.3

**Comment by hertschuh** [comment]
@vikkubaligas ,

Please upgrade to tf 2.17.0 and keras 3.5.0. The problem is resolved with those versions.

Thanks.
