### ISSUE TITLE
Add Levenberg-Marquardt algorithm as a optimizer for keras.

### ISSUE THREAD

**Issue by Fly-Playgroud** [keras-team/tf-keras#628]
Hi！please add` Levenberg-Marquardt` algorithm as a optimizer for keras. This algorithm is great useful for some problems.

**Comment by JohnTaylor2000** [comment]
All,

I agree that an integrated version would be very useful for many applications eg time series, PINNs etc and does not require tuning many hyperparameters and can result in much smaller, more efficient, models.

John

From: BUG-Fly ***@***.***>
Date: Saturday, 23 September 2023 at 4:21 am
To: keras-team/tf-keras ***@***.***>
Cc: Taylor, John (Data61, Black Mountain) ***@***.***>, Mention ***@***.***>
Subject: [keras-team/tf-keras] Add Levenberg-Marquardt algorithm as a optimizer for keras. (Issue #628)

Hi！please add Levenberg-Marquardt algorithm as a optimizer for keras. This algorithm is great useful for some problems.
