### ISSUE TITLE
NotFoundError could not find registered transfer manager for platform Host -- check target linkage [Op:__inference__jit_compiled_convolution_op_26169]

### ISSUE THREAD

**Issue by innat** [keras-team/tf-keras#655]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): kaggle
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.12
- Python version:
- Bazel version (if compiling from source):
- GPU model and memory: TPU-VM
- Exact command to reproduce:

**Describe the problem**.

Describe the problem clearly here. Be sure to convey here why it's a bug in TF-Keras or why the requested feature is needed.

**Describe the current behavior**.

I was trying to use `groups` parameter from `keras.layers.Conv2D` API on TPU-VM device. While running on GPU works but on TPU, it doesn't if `groups > 1`.

**Describe the expected behavior**.

It should work, unless if there is an known issue for `groups > 1` for TPU.

**Standalone code to reproduce the issue**.

```python
input_shape = (4, 28, 28, 9)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(
    27, 3, activation='relu', input_shape=input_shape[1:], groups=3
)(x)
print(y.shape)
```
```yaml
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
Cell In[133], line 3
      1 input_shape = (4, 28, 28, 9)
      2 x = tf.random.normal(input_shape)
----> 3 y = tf.keras.layers.Conv2D(
      4     27, 3, activation='relu', input_shape=input_shape[1:], groups=3
      5 )(x)
      7 print(y.shape)

File /usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /usr/local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py:52, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     50 try:
     51   ctx.ensure_initialized()
---> 52   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     53                                       inputs, attrs, num_outputs)
     54 except core._NotOkStatusException as e:
     55   if name is not None:

NotFoundError: Exception encountered when calling layer 'conv2d_335' (type Conv2D).

could not find registered transfer manager for platform Host -- check target linkage [Op:__inference__jit_compiled_convolution_op_26236]

Call arguments received by layer 'conv2d_335' (type Conv2D):
  • inputs=tf.Tensor(shape=(4, 28, 28, 9), dtype=float32)
```

**Comment by innat** [comment]
A bit confusing, if I run the above code block on colab-tpu pod, it works but it doesn't on the kaggle tpu-vm. 

gist: https://www.kaggle.com/code/ipythonx/github-issue-655-keras-tpu-vm/notebook

Hello @djherbis, could you please add something here? I think it's somewhat related to hardware issue, not sure.

**Comment by djherbis** [comment]
@innat TPU nodes (Colab) and TPU VMs are quite different in my experience.

The TPU node is basically a Tensorflow server you send tf code to execute on, vs. the TPU VM has the TPU directly connected to the VM so instructions run "locally".

Because of this TPU nodes can be talked to with "stock" tensorflow, but TPU VMs use a specialized tensorflow library to talk directly to the TPU.

Its probably best to report these issues to the Tensorflow team directly https://github.com/tensorflow/tensorflow I don't see if they have a TPU VM specific contact anywhere but I'd call out that it happens on TPU VM.

**Comment by innat** [comment]
Thanks @djherbis for the explanation. As you suggested, I create a separate ticket in tensorflow.  https://github.com/tensorflow/tensorflow/issues/61976
