### ISSUE TITLE
AttributeError: module 'tf_keras.backend' has no attribute 'logsumexp'

### ISSUE THREAD

**Issue by gitfourteen** [keras-team/tf-keras#769]
In colab, first `pip install tf-keras` , then
```
import tf-keras as keras
dir(keras.backend) #No logsumexp
keras.backend.backend() #tensorflow

from keras import backend as K
K.logsumexp #AttributeError

import tensorflow as tf
tf.__version__ #2.15.0
keras.__version__ #2.15.1
```

No `logsumexp` found, but still [there is](https://github.com/keras-team/tf-keras/blob/master/tf_keras/backend.py#L3076).
How to get this function?

**Comment by tilakrayal** [comment]
@gitfourteen,
Thank you for reporting the issue. We are looking into the same. Could you please allow some time to analyse and debug the issue and provide the resolution. Thank you!

**Comment by tilakrayal** [comment]
@gitfourteen,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

**Comment by gitfourteen** [comment]
> @gitfourteen,
> Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

Thanks for your reply. `from keras import backend as K` do include `logsumexp` in early days before Keras merging into Tensorflow and this is routine going to backend, e.g., [here](https://github.com/bojone/crf/blob/master/crf_keras.py#L33), [here](https://github.com/artemyk/ibsgd/blob/master/demo.py#L25) and [here](https://github.com/Healthcare-Robotics/mr-gan/blob/master/mr_gan.py#L148), etc. However `backend` of Keras became inconsistent since Keras 2, I think? See [this issue](https://github.com/keras-team/keras/issues/14647#issuecomment-963769610) reported 3 years ago. 

In a word,  since `logsumexp` is not decorated as others in `backend`,  how can we import `logsumexp` in Keras 2?

**Comment by tilakrayal** [comment]
@gitfourteen,
**logsumexp** method was deprecated from keras.backend. Please use it the same function under TF. Please check [here](https://www.tensorflow.org/api_docs/python/tf/math/reduce_logsumexp) for more information. Thank you!
