### ISSUE TITLE
Showing warning just after importing tf_keras

### ISSUE THREAD

**Issue by kr-Ayaman** [keras-team/tf-keras#778]
when i run the code
`import tf_keras`

the out output is

> WARNING:tensorflow:From C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

I am not even using tensorflow library but I still get this warning

**Comment by tilakrayal** [comment]
@kr-Ayaman,
Apologies for the delay. Could you please confirm which version of tf-keras you are trying and the TensorFlow version as well. AFAIK  it is possible that **tf.compat.v1.losses.sparse_softmax_cross_entropy** which calls the older **tf.losses.sparse_softmax_cross_entropy** and this causes the deprecation warning to trigger.

The deprecations are added as decorators, so they trigger at import time when the module is parsed and I suspect that is for the eager.

**Comment by kr-Ayaman** [comment]
I am using tf-keras version 2.16.0 and tensorflow version 2.16.1

**Comment by tilakrayal** [comment]
@kr-Ayaman,
COuld you please let us know in which environment you are facing the mentioned warning? I tried in the colab and could not find the warning. Thank you!
