### ISSUE TITLE
Missing github release of 2.17

### ISSUE THREAD

**Issue by jonas-eschle** [keras-team/tf-keras#796]
It seems that a github release is missing (and we would need this in [spack](https://github.com/spack/spack)).

Could you make a release of the 2.17?

Many thanks!

**Comment by tilakrayal** [comment]
@jonas-eschle,
Could you please provide more info/context for the above mentioned issue? Thank you!

**Comment by jonas-eschle** [comment]
Hi @tilakrayal there is not a lot to add to it: some package-managers simlpy rely on the github release, so it would be nice to keep it up. We actually needed it for spack, but we can work around it.

It rather seems like something was forgotten, as there has always been a github release otherwise.
