### ISSUE TITLE
Please merge pull request 779

### ISSUE THREAD

**Issue by bernhardkaindl** [keras-team/tf-keras#804]
Please merge the approved PR https://github.com/keras-team/tf-keras/pull/779, many thanks!

It has been approved for 5 months.

It blocks the Spack package manager (https://spack.io/) from progressing to support `tf-keras` on a chain of PRs,
starting with https://github.com/spack/spack/pull/43688.

What does it take to merge the PR?

Many thanks 
Bernhard
(external project contributor)

**Comment by bernhardkaindl** [comment]
@fchollet, could you help with this (assigning a developer to merge the PR)?

**Comment by tilakrayal** [comment]
@bernhardkaindl,
The mentioned PR https://github.com/keras-team/tf-keras/pull/779 has been reviewed and merged. Could you please check and confirm the same. Thank you!

**Comment by bernhardkaindl** [comment]
@tilakrayal Thanks, yes, it is merged!

@jonas-eschle started working on https://github.com/spack/spack/pull/43688, thanks!
